export const GRID_MAP = {
  "row-1-col-1": false,
  "row-1-col-2": false,
  "row-1-col-3": false,
  "row-1-col-4": false,
  "row-1-col-5": false,

  "row-2-col-1": false,
  "row-2-col-2": false,
  "row-2-col-3": false,
  "row-2-col-4": false,
  "row-2-col-5": false,

  "row-3-col-1": false,
  "row-3-col-2": false,
  "row-3-col-3": false,
  "row-3-col-4": false,
  "row-3-col-5": false,

  "row-4-col-1": false,
  "row-4-col-2": false,
  "row-4-col-3": false,
  "row-4-col-4": false,
  "row-4-col-5": false,

  "row-5-col-1": false,
  "row-5-col-2": false,
  "row-5-col-3": false,
  "row-5-col-4": false,
  "row-5-col-5": false,
};

export const TEXT_GRID_MAP = {
  1: [
    "row-1-col-1",
    "row-2-col-1",
    "row-3-col-1",
    "row-4-col-1",
    "row-5-col-1",
  ],
  5: [
    "row-1-col-5",
    "row-1-col-4",
    "row-1-col-3",
    "row-2-col-3",
    "row-3-col-3",
    "row-3-col-4",
    "row-3-col-5",
    "row-4-col-5",
    "row-5-col-5",
    "row-5-col-4",
    "row-5-col-3",
  ],
  Y: [
    "row-1-col-1",
    "row-2-col-2",
    "row-3-col-3",
    "row-2-col-4",
    "row-1-col-5",
    "row-4-col-3",
    "row-5-col-3",
  ],
  E: [
    "row-1-col-2",
    "row-1-col-3",
    "row-1-col-4",
    "row-2-col-2",
    "row-3-col-2",
    "row-3-col-3",
    "row-4-col-2",
    "row-5-col-2",
    "row-5-col-3",
    "row-5-col-4",
  ],
  A: [
    "row-5-col-2",
    "row-4-col-2",
    "row-3-col-2",
    "row-2-col-2",
    "row-1-col-3",
    "row-2-col-4",
    "row-3-col-4",
    "row-4-col-4",
    "row-5-col-4",
    "row-3-col-3",
  ],
  R: [
    "row-5-col-2",
    "row-4-col-2",
    "row-3-col-2",
    "row-2-col-2",
    "row-1-col-2",
    "row-1-col-3",
    "row-1-col-4",
    "row-2-col-4",
    "row-3-col-4",
    "row-3-col-3",
    "row-4-col-3",
    "row-3-col-3",
    "row-5-col-4",
  ],
  S: [
    "row-1-col-4",
    "row-1-col-3",
    "row-1-col-2",
    "row-2-col-2",
    "row-3-col-2",
    "row-3-col-3",
    "row-3-col-4",
    "row-4-col-4",
    "row-5-col-4",
    "row-5-col-3",
    "row-5-col-2",
  ],
  O: [
    "row-1-col-2",
    "row-2-col-2",
    "row-3-col-2",
    "row-4-col-2",
    "row-5-col-2",
    "row-5-col-3",
    "row-5-col-4",
    "row-4-col-4",
    "row-3-col-4",
    "row-2-col-4",
    "row-1-col-4",
    "row-1-col-3",
  ],
  F: [
    "row-1-col-2",
    "row-1-col-3",
    "row-1-col-4",
    "row-2-col-2",
    "row-3-col-2",
    "row-3-col-3",
    "row-4-col-2",
    "row-5-col-2",
  ],
  E2: [
    "row-1-col-2",
    "row-1-col-3",
    "row-1-col-4",
    "row-2-col-2",
    "row-3-col-2",
    "row-3-col-3",
    "row-4-col-2",
    "row-5-col-2",
    "row-5-col-3",
    "row-5-col-4",
  ],
  S2: [
    "row-1-col-4",
    "row-1-col-3",
    "row-1-col-2",
    "row-2-col-2",
    "row-3-col-2",
    "row-3-col-3",
    "row-3-col-4",
    "row-4-col-4",
    "row-5-col-4",
    "row-5-col-3",
    "row-5-col-2",
  ],
  A2: [
    "row-5-col-2",
    "row-4-col-2",
    "row-3-col-2",
    "row-2-col-2",
    "row-1-col-3",
    "row-2-col-4",
    "row-3-col-4",
    "row-4-col-4",
    "row-5-col-4",
    "row-3-col-3",
  ],
  N: [
    "row-5-col-1",
    "row-4-col-1",
    "row-3-col-1",
    "row-2-col-1",
    "row-1-col-1",
    "row-2-col-2",
    "row-3-col-3",
    "row-4-col-4",
    "row-5-col-5",
    "row-4-col-5",
    "row-3-col-5",
    "row-2-col-5",
    "row-1-col-5",
  ],
  D: [
    "row-1-col-2",
    "row-2-col-2",
    "row-3-col-2",
    "row-4-col-2",
    "row-5-col-2",
    "row-5-col-3",
    "row-5-col-4",
    "row-4-col-4",
    "row-3-col-4",
    "row-2-col-4",
    "row-1-col-4",
    "row-1-col-3",
  ],
  S3: [
    "row-1-col-4",
    "row-1-col-3",
    "row-1-col-2",
    "row-2-col-2",
    "row-3-col-2",
    "row-3-col-3",
    "row-3-col-4",
    "row-4-col-4",
    "row-5-col-4",
    "row-5-col-3",
    "row-5-col-2",
  ],
  U: [
    "row-1-col-2",
    "row-2-col-2",
    "row-3-col-2",
    "row-4-col-2",
    "row-5-col-2",
    "row-5-col-3",
    "row-5-col-4",
    "row-4-col-4",
    "row-3-col-4",
    "row-2-col-4",
    "row-1-col-4",
  ],
  B: [
    "row-5-col-2",
    "row-4-col-2",
    "row-3-col-2",
    "row-2-col-2",
    "row-1-col-2",
    "row-1-col-3",
    "row-1-col-4",
    "row-2-col-4",
    "row-3-col-4",
    "row-3-col-3",
    "row-4-col-4",
    "row-5-col-4",
    "row-5-col-3",
  ],
  B2: [
    "row-5-col-2",
    "row-4-col-2",
    "row-3-col-2",
    "row-2-col-2",
    "row-1-col-2",
    "row-1-col-3",
    "row-1-col-4",
    "row-2-col-4",
    "row-3-col-4",
    "row-3-col-3",
    "row-4-col-4",
    "row-5-col-4",
    "row-5-col-3",
  ],
  U2: [
    "row-1-col-2",
    "row-2-col-2",
    "row-3-col-2",
    "row-4-col-2",
    "row-5-col-2",
    "row-5-col-3",
    "row-5-col-4",
    "row-4-col-4",
    "row-3-col-4",
    "row-2-col-4",
    "row-1-col-4",
  ],
  EMPTY: [],
};
